In [46]:
#create any 3 dimensional array and practice indexing
import numpy as np
a = np.array([[[0, 1, 2], [3, 4, 5]],[[0, 1, 2], [3, 4, 5]]])
print(a)
print('-----------------------')
a[0,1]=10
print(a)
print('-----------------------')
a[0,1,1]=17
print(a)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
-----------------------
[[[ 0  1  2]
  [10 10 10]]

 [[ 0  1  2]
  [ 3  4  5]]]
-----------------------
[[[ 0  1  2]
  [10 17 10]]

 [[ 0  1  2]
  [ 3  4  5]]]


In [ ]:
a[1,1,1]=12
print(a)
print('-----------------------')
a[0,0,0]=9
a[1,0,00]=4
print(a)

[[[ 9  1  2]
  [10 17 10]]

 [[ 4  1  2]
  [ 3 12  5]]]
-----------------------
[[[ 9  1  2]
  [10 17 10]]

 [[ 4  1  2]
  [ 3 12  5]]]


In [44]:
#create array of suqares of keys of below dictionary
#d = {1:2,2:3,3:4,4:5}
d = {1:2,2:3,3:4,4:5}
# to return a group of the key-value
# pairs in the dictionary
result = d.keys()
print(result)
# Convert object to a list
data = list(result)
# Convert list to an array
Array = np.array(data)
# print the numpy array
print(Array)
print( 'array of suqares of keys of  dictionary is')
A=Array**2
A


dict_keys([1, 2, 3, 4])
[1 2 3 4]
array of suqares of keys of  dictionary is


array([ 1,  4,  9, 16])

In [45]:
# multiply any 2 dim array to identity matrix (2*2) and comment on result
import numpy as np
print('2 dim array')
a=np.array([[3,5],[6,8]])
print(a)
print('\n identity matrix(2*2)')
b=np.eye(2)
print(b)
print('\nmultiplication of 2 matrix is')
print(a*b)

2 dim array
[[3 5]
 [6 8]]

 identity matrix(2*2)
[[1. 0.]
 [0. 1.]]

multiplication of 2 matrix is
[[3. 0.]
 [0. 8.]]
